import { chromium } from 'playwright';
const S = process.env.S;
const browser = await chromium.launch({ executablePath: '/opt/pw-browsers/chromium' });
const page = await browser.newPage({ viewport: { width: 1100, height: 1400 } });
const errors = [];
page.on('pageerror', (e) => errors.push('pageerror: ' + e.message));
await page.goto('http://127.0.0.1:3777/', { waitUntil: 'networkidle' });
await page.waitForSelector('#quoteRows .quote-row', { timeout: 60000 });
await page.waitForTimeout(1500);
console.log('title:', await page.title());
console.log('badges:', (await page.locator('.topbar').innerText()).replace(/\n/g,' '));
console.log('summary:', (await page.locator('.summary').innerText()).replace(/\n/g,' '));
console.log('fee tiers:', (await page.locator('#feeTier').innerText()).replace(/\n/g,' | '));
await page.screenshot({ path: `${S}/final-launch.png`, fullPage: true });
await page.click('.tabbtn[data-tab="explore"]');
await page.waitForFunction(() => !document.querySelector('#feedMsg').innerText.includes('scanning'), null, { timeout: 120000 });
console.log('feed:', await page.locator('#feedMsg').innerText());
await page.screenshot({ path: `${S}/final-explore.png`, fullPage: true });
console.log('errors', errors);
await browser.close();
